apiVersion: 1

datasources:
  - name: ScenarioBench InfluxDB
    uid: scenariobench-influxdb
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: nbomber
    user: nbomber
    secureJsonData:
      password: nbomber
    jsonData:
      httpMode: GET
    isDefault: true
    editable: true
